language: node_js
sudo: required
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master

addons:
  chrome: stable
    
cache:
  directories:
  - node_modules

before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
- npm install
- npm install -g @angular/cli

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

scripts:
  - yarn lint


