language: node_js
sudo: required
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master

addons:
  chrome: stable
  ssh_known_hosts: 92.222.9.74

cache:
  directories:
    - node_modules

before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - npm install -g @angular/cli@7.0.5

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

scripts:
  - yarn lint

before_deploy:
  - openssl aes-256-cbc -K $encrypted_7c98c3dda81a_key -iv $encrypted_7c98c3dda81a_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:8181/deploy/applitrami-front
  on:
    branch: master
  endpoint: https://api.travis-ci.org